CREATE TABLE inventory_items (
    product_id  VARCHAR(64) PRIMARY KEY,
    total_stock BIGINT NOT NULL
);

CREATE TABLE reservations (
    order_id   VARCHAR(64) PRIMARY KEY,
    product_id VARCHAR(64) NOT NULL,
    quantity   BIGINT      NOT NULL,
    status     VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE outbox (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     VARCHAR(64)  NOT NULL,
    type         VARCHAR(64)  NOT NULL,
    msg_key      VARCHAR(64)  NOT NULL,
    payload      TEXT         NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    published_at TIMESTAMPTZ
);

CREATE TABLE processed_events (
    event_id     VARCHAR(64) PRIMARY KEY,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
